# Generated by Django 4.1.4 on 2022-12-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password_hash', models.CharField(max_length=20)),
                ('date_registration', models.DateField(auto_now_add=True)),
                ('date_activity', models.DateField()),
            ],
        ),
    ]
